### ISSUE TITLE
Android dependency problem

### ISSUE THREAD

**Issue by AndreHaueisen** [lubritto/Flutter_Documents_Picker#1]
Hi, I'm trying to test your plugin, but I'm getting a dependency message error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:appcompat-v7' has different version for the compile (27.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
```

Not sure how to solve it.

**Comment by AndreHaueisen** [comment]
I found the issue.
Flutter official plugins still uses `com.android.support:appcompat-v7:27.1.0` and yours uses `com.android.support:appcompat-v7:27.1.1`.
This is not a problem with your plugin then. Feel free to close this.
I will try to configure Gradle to get pass this contradiction.

**Comment by AndreHaueisen** [comment]
Solved it simply by adding 
`implementation 'com.android.support:appcompat-v7:27.1.1` and `implementation 'com.android.support:support-v4:27.1.1` to the `build.gradle` file

**Comment by lubritto** [comment]
Thanks for tip!
